version: "3"

services:
    ctf18:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/root/pwd
        command:
            - /bin/zsh
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined
